import crypto from 'node:crypto';
import { aiEnabled, invokeLLM } from '../ai/claude.js';
import { config } from '../config.js';
import { objectKey, putObject } from '../files/objectStore.js';
import { HttpError, badRequest, notFound } from '../lib/errors.js';
import { log as defaultLog } from '../lib/logger.js';
import { mapPool } from '../lib/pool.js';
import { concatMp3 } from '../media/mp3.js';
import { generateNarration, generateVideo, mediaEnabled, mediaUnavailableError } from '../media/index.js';
import { entities } from '../repo/entities.js';
import { asHttpError, errMsg, withLessonLock } from './util.js';

// generateLessonMedia — turns a lesson's teaching script into a scene-by-scene explainer video.
// The script is split into scenes; each scene gets its own narration audio and an explainer slide —
// a heading and key points written for exactly what that part says — plus subtitle cues timed to it.
// The narration parts are joined into one track, and lesson.video_scenes records when each scene
// starts and ends, its slide and its captions, so the player draws the slides in step with the voice.
// With MEDIA_SCENE_CLIPS=true each scene also gets a generated clip, shown as a muted backdrop.
// Generated bytes live in the object store and are served from /api/media/<key>.
//
// Payload: { lesson_id, slides_only? }  slides_only: rebuild slides + captions, keep the narration
// Returns: { ok: true, lesson_id, video_url, audio_url, scenes, video_error?, audio_error? }

const MAX_NARRATION_CHARS = 5000;
const CHARS_PER_SCENE = 600; // ≈ 35–45 s of speech
const ATTEMPTS = 2;
const VOICE = 'storm';
const CLIP_CONCURRENCY = 3;

async function withRetry(label, fn, log, attempts = ATTEMPTS) {
  let lastErr;
  for (let i = 1; i <= attempts; i++) {
    try {
      return await fn();
    } catch (e) {
      lastErr = e;
      log.warn('pipeline.media.attempt_failed', { kind: label, attempt: i, of: attempts, error: errMsg(e) });
      if (i < attempts) await new Promise((r) => setTimeout(r, 1500 * i));
    }
  }
  throw lastErr instanceof Error ? lastErr : new Error(String(lastErr));
}

/** Trim narration to the limit at a sentence boundary where possible. */
export function narrationText(text) {
  const clean = String(text || '').replace(/\s+/g, ' ').trim();
  if (clean.length <= MAX_NARRATION_CHARS) return clean;
  const cut = clean.slice(0, MAX_NARRATION_CHARS);
  const lastStop = Math.max(cut.lastIndexOf('. '), cut.lastIndexOf('? '), cut.lastIndexOf('! '));
  return lastStop > MAX_NARRATION_CHARS * 0.6 ? cut.slice(0, lastStop + 1) : cut;
}

export function sceneCount(text, max = config.mediaMaxScenes) {
  return Math.max(1, Math.min(max, Math.round(String(text || '').length / CHARS_PER_SCENE) || 1));
}

/** Splits narration into `n` consecutive parts of similar length, only at sentence ends. */
export function splitNarration(text, n) {
  const sentences = String(text || '').match(/[^.!?]+(?:[.!?]+["')\]]*|$)/g)?.map((s) => s.trim()).filter(Boolean) || [];
  if (n <= 1 || sentences.length <= 1) return sentences.length ? [sentences.join(' ')] : [];
  const parts = Math.min(n, sentences.length);
  const total = sentences.reduce((s, x) => s + x.length, 0);
  const out = [];
  let current = [];
  let used = 0;
  sentences.forEach((s, i) => {
    current.push(s);
    used += s.length;
    const remainingParts = parts - out.length - 1;
    const remainingSentences = sentences.length - i - 1;
    const target = (total * (out.length + 1)) / parts;
    if (remainingParts > 0 && (used >= target || remainingSentences === remainingParts)) {
      out.push(current.join(' '));
      current = [];
    }
  });
  if (current.length) out.push(current.join(' '));
  return out;
}

const keyPoints = (lesson) => String(lesson.key_points || '')
  .split('\n')
  .map((l) => l.replace(/^[-*•\d.)\s]+/, '').trim())
  .filter(Boolean)
  .slice(0, 5);

// Fixed look for every clip, so a course's videos feel like one series.
const STYLE = [
  'Absolutely no text of any kind: no words, labels, captions, titles, letters or numbers anywhere in the frame.',
  'Style: clean modern motion graphics — animated technical diagrams, schematics and flow arrows that build up step by step.',
  'Colour palette: deep indigo and violet gradients with white and soft lavender accents on a dark indigo background, professional corporate-tech look.',
  'Smooth camera moves, crisp vector shapes, subtle glow.',
  'No people or faces, no logos or watermarks, nothing unrelated to the lesson topic.',
  'Silent video — no audio, no music, no voice. One continuous 8-second shot, 16:9 landscape.',
].join(' ');

/** Deterministic prompt from the lesson's own fields (used when AI is off or the storyboard fails). */
export function buildVideoPrompt(lesson, segment = '') {
  const points = keyPoints(lesson);
  return [
    `Educational explainer video for an engineering training lesson titled "${lesson.video_title || lesson.title}".`,
    lesson.source_section || lesson.source_chapter ? `It comes from the playbook section "${lesson.source_section || lesson.source_chapter}".` : '',
    lesson.teaching_objective ? `Learning goal: ${lesson.teaching_objective}.` : '',
    segment ? `This scene illustrates: ${segment.slice(0, 500)}` : lesson.summary ? `Topic: ${String(lesson.summary).slice(0, 400)}` : '',
    !segment && points.length ? `Visualize these ideas: ${points.join('; ')}.` : '',
    STYLE,
  ].filter(Boolean).join(' ');
}

/** Short on-screen caption for a scene when the storyboard can't be written by the AI. */
export function fallbackTitle(segment, index) {
  const words = String(segment || '').replace(/[^\p{L}\p{N}\s'-]/gu, ' ').split(/\s+/).filter(Boolean).slice(0, 6);
  return words.length ? words.join(' ') : `Part ${index + 1}`;
}

// ---- slides ---------------------------------------------------------------------------------------
// Every scene is an explainer slide the player draws as crisp text: a heading, two to four key points
// in the lesson's own terms, and subtitles of exactly what is being said. Slide layouts:
//   points — key ideas as a list        steps — an ordered process, drawn as numbered stages
export const SLIDE_LAYOUTS = ['points', 'steps'];
const MAX_POINT_CHARS = 110;

const clip = (text, max) => {
  const t = String(text || '').replace(/\s+/g, ' ').trim();
  if (t.length <= max) return t;
  const cut = t.slice(0, max);
  return `${cut.slice(0, Math.max(cut.lastIndexOf(' '), max * 0.6)).replace(/[\s,;:–-]+$/, '')}…`;
};

const sentencesOf = (text) => String(text || '').match(/[^.!?]+(?:[.!?]+["')\]]*|$)/g)?.map((s) => s.trim()).filter(Boolean) || [];

/** Key points for a slide when the AI storyboard is unavailable: the part's own sentences. */
export function fallbackPoints(segment) {
  return sentencesOf(segment).slice(0, 3).map((s) => clip(s.replace(/[.!?]+$/, ''), MAX_POINT_CHARS));
}

const MAX_CUE_CHARS = 84; // two short lines at the bottom of the frame

/** Breaks one sentence into subtitle-sized pieces, preferring clause boundaries over word breaks. */
function cueChunks(sentence) {
  if (sentence.length <= MAX_CUE_CHARS) return [sentence];
  const out = [];
  let rest = sentence;
  while (rest.length > MAX_CUE_CHARS) {
    const window = rest.slice(0, MAX_CUE_CHARS + 1);
    const clause = Math.max(window.lastIndexOf(', '), window.lastIndexOf('; '), window.lastIndexOf(': '), window.lastIndexOf(' – '), window.lastIndexOf(' — '));
    const at = clause > MAX_CUE_CHARS * 0.4 ? clause + 1 : window.lastIndexOf(' ');
    const cut = at > 0 ? at : MAX_CUE_CHARS;
    out.push(rest.slice(0, cut).trim());
    rest = rest.slice(cut).trim();
  }
  if (rest) out.push(rest);
  return out;
}

/**
 * Subtitle cues for one narrated part: its words, cut into subtitle-sized pieces and spread over the
 * part's time span in proportion to their length — speech runs at a near-constant rate, and each part
 * is narrated on its own, so the timing stays close within a part and resets exactly at the next.
 */
export function buildCaptions(segment, start, end) {
  const chunks = sentencesOf(segment).flatMap(cueChunks).filter(Boolean);
  if (!chunks.length || !(end > start)) return [];
  const weights = chunks.map((c) => c.length + 8); // +8: the pause at each break
  const total = weights.reduce((a, b) => a + b, 0);
  let t = start;
  return chunks.map((text, i) => {
    const cueEnd = i === chunks.length - 1 ? end : t + ((end - start) * weights[i]) / total;
    const cue = { start: +t.toFixed(2), end: +cueEnd.toFixed(2), text };
    t = cueEnd;
    return cue;
  });
}

const STORYBOARD_SCHEMA = {
  type: 'object',
  properties: {
    scenes: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          title: { type: 'string', description: 'Slide heading, 2–7 words' },
          layout: { type: 'string', enum: SLIDE_LAYOUTS, description: 'steps for an ordered process or sequence, otherwise points' },
          points: { type: 'array', items: { type: 'string' }, description: '2–4 key points (up to 5 for steps), each at most 14 words' },
          visual: { type: 'string', description: 'Only when asked: the brief for a silent background clip, 40–100 words' },
        },
        required: ['title', 'layout', 'points'],
      },
    },
  },
  required: ['scenes'],
};

/**
 * One LLM call turns the narration parts into a slide deck: for each part, the heading and key points
 * a professional explainer would put on screen while that part is spoken.
 */
export async function buildStoryboard(lesson, segments, { clips = false } = {}) {
  const points = keyPoints(lesson);
  const prompt = [
    `Design the on-screen slides for a professional explainer video of the engineering lesson "${lesson.video_title || lesson.title}". The narration is split into ${segments.length} consecutive parts; each part is shown as one slide while it is spoken, with subtitles underneath.`,
    lesson.source_section || lesson.source_chapter ? `Playbook section: ${lesson.source_section || lesson.source_chapter}` : '',
    lesson.teaching_objective ? `Learning goal: ${lesson.teaching_objective}` : '',
    points.length ? `Lesson key points:\n- ${points.join('\n- ')}` : '',
    '',
    ...segments.map((s, i) => `Part ${i + 1}: ${s}`),
    '',
    `Return exactly ${segments.length} slides, in order, one per part.`,
    'For each slide:',
    '- title: a 2–7 word heading naming what this part teaches, using the lesson\'s real terms. Never promise a count the slide does not show (no "Five Uses" over three points).',
    '- layout: "steps" when the part walks through an ordered process, stages or sequence; otherwise "points".',
    '- points: 2–4 short key points (up to 5 for steps, so a process is shown whole; at most 14 words each) that summarise what THIS part says — its specific terms, components, rules and reasons — in the order they are spoken. Faithful to the narration: no facts, numbers or claims it does not make, no filler, no marketing tone, no trailing full stops.',
    clips
      ? '- visual: a silent 8-second background clip for the slide: one abstract technical motion-graphic matching the idea (shapes, flows, structure), with no text, letters, numbers, people or logos in it.'
      : '- visual: leave empty.',
  ].filter(Boolean).join('\n');
  const { scenes } = await invokeLLM({ prompt, schema: STORYBOARD_SCHEMA, maxTokens: 6000, effort: 'medium' });
  if (!Array.isArray(scenes) || scenes.length !== segments.length) throw new Error(`storyboard returned ${scenes?.length ?? 0} of ${segments.length} scenes`);
  return scenes.map((s, i) => {
    const slidePoints = (Array.isArray(s.points) ? s.points : [])
      .map((p) => clip(String(p).replace(/^[-*•\d.)\s]+/, '').replace(/[.]+$/, ''), MAX_POINT_CHARS))
      .filter((p) => p.length >= 3)
      .slice(0, s.layout === 'steps' ? 5 : 4);
    if (!slidePoints.length) throw new Error(`storyboard slide ${i + 1} has no points`);
    const visual = String(s.visual || '').replace(/\s+/g, ' ').trim();
    return {
      title: clip(s.title, 60) || fallbackTitle(segments[i], i),
      layout: SLIDE_LAYOUTS.includes(s.layout) ? s.layout : 'points',
      points: slidePoints,
      prompt: visual.length >= 40 ? `${visual.slice(0, 1200)} ${STYLE}` : buildVideoPrompt(lesson, segments[i]),
    };
  });
}

/** The scenes a lesson already has (for a slides-only rebuild that keeps its narration). */
function existingScenes(lesson) {
  try {
    const raw = typeof lesson.video_scenes === 'string' ? JSON.parse(lesson.video_scenes || '[]') : lesson.video_scenes;
    return Array.isArray(raw) ? raw.filter((s) => Number.isFinite(+s?.start) && Number.isFinite(+s?.end)) : [];
  } catch {
    return [];
  }
}

// Provider result → URL stored on the lesson.
async function store(lessonId, kind, res) {
  if (res.url) return res.url;
  const hash = crypto.createHash('sha256').update(res.bytes).digest('hex');
  const key = objectKey('media', lessonId, kind, hash);
  await putObject(key, res.bytes, { source: 'media', kind, lesson_id: lessonId, content_type: res.contentType });
  return `/api/media/${key}`;
}

/** Narration for every part, joined into one MP3; returns its URL and each part's time span. */
async function narrate(lessonId, segments, log) {
  const results = await mapPool(segments, 4, (text, i) => withRetry(`audio ${i + 1}`, () => generateNarration({ text, voice: VOICE }), log));
  const failed = results.find((r) => !r.ok);
  if (failed) throw failed.error;
  const parts = results.map((r) => r.value);
  if (parts.some((p) => !p.bytes)) {
    // A provider that only returns URLs can't be joined; fall back to one track for the whole script.
    throw new Error('Media provider returned narration URLs that cannot be joined');
  }
  const joined = concatMp3(parts.map((p) => p.bytes));
  if (!joined.seconds) throw new Error('Narration audio could not be read');
  const url = await store(lessonId, 'audio', { bytes: joined.bytes, contentType: 'audio/mpeg' });
  return { url, spans: joined.spans, seconds: joined.seconds };
}

export default async function generateLessonMedia(payload = {}, ctx = {}) {
  const lessonId = payload?.lesson_id ? String(payload.lesson_id) : '';
  if (!lessonId) throw badRequest('lesson_id is required');
  return withLessonLock(lessonId, () => generate(payload, ctx));
}

async function generate(payload = {}, ctx = {}) {
  const log = ctx.log || defaultLog;
  const lessonId = payload?.lesson_id ? String(payload.lesson_id) : '';
  if (!lessonId) throw badRequest('lesson_id is required');
  // slides_only rebuilds the slides and subtitles over the narration the lesson already has — no new
  // audio or clips, so no media provider and no media credits.
  const slidesOnly = payload?.slides_only === true;
  if (!mediaEnabled() && !slidesOnly) throw mediaUnavailableError();

  const sr = entities;
  const lesson = await sr.Lesson.get(lessonId);
  if (!lesson) throw notFound('Lesson not found');
  // Media is made from the lesson's content; without it the clips and narration would be generic.
  if (!String(lesson.teaching_script || '').trim() && !String(lesson.summary || '').trim()) {
    throw badRequest('Generate the lesson content first — the video and narration are made from its teaching script.');
  }

  const narration = narrationText(lesson.teaching_script || lesson.summary);
  // A slides-only rebuild needs the script split exactly as it was when the narration was recorded.
  const recorded = slidesOnly ? existingScenes(lesson) : [];
  let segments;
  if (slidesOnly) {
    if (!lesson.audio_url || !recorded.length) throw badRequest('This lesson has no scene narration yet — generate media first.');
    segments = splitNarration(narration, recorded.length);
    const drifted = segments.length !== recorded.length || recorded.some((s, i) => s.text && s.text !== segments[i]);
    if (drifted) throw badRequest('The teaching script changed since the narration was recorded — regenerate media instead.');
  } else {
    segments = splitNarration(narration, sceneCount(narration));
  }
  const withClips = config.mediaSceneClips && !slidesOnly;

  try {
    await sr.Lesson.update(lessonId, { status: 'generating' });

    let storyboard = segments.map((s, i) => ({ title: fallbackTitle(s, i), layout: 'points', points: fallbackPoints(s), prompt: buildVideoPrompt(lesson, s) }));
    if (aiEnabled()) {
      try {
        storyboard = await buildStoryboard(lesson, segments, { clips: withClips });
      } catch (e) {
        log.warn('pipeline.media.storyboard_failed', { lesson_id: lessonId, error: errMsg(e) });
      }
    }

    const [audioRes, clipRes] = await Promise.allSettled([
      slidesOnly
        ? Promise.resolve({ url: lesson.audio_url, spans: recorded.map((s) => ({ start: +s.start, end: +s.end })), seconds: +recorded.at(-1).end })
        : narrate(lessonId, segments, log),
      withClips
        ? mapPool(storyboard, CLIP_CONCURRENCY, (scene, i) => withRetry(`video ${i + 1}`, async () => store(
          lessonId, 'video', await generateVideo({ prompt: scene.prompt, durationSeconds: 8, aspectRatio: '16:9' }),
        ), log))
        : Promise.resolve([]),
    ]);

    const clips = clipRes.status === 'fulfilled' ? clipRes.value : [];
    const clipUrls = withClips ? clips.map((c) => (c.ok ? c.value : null)) : storyboard.map(() => null);
    const clipErrors = clips.filter((c) => !c.ok).map((c) => errMsg(c.error));
    const audio = audioRes.status === 'fulfilled' ? audioRes.value : null;
    const audioError = audioRes.status === 'rejected' ? errMsg(audioRes.reason) : undefined;
    const videoError = !withClips || clipUrls.some(Boolean)
      ? (clipErrors.length ? `${clipErrors.length} of ${storyboard.length} scene clips failed: ${clipErrors[0]}` : undefined)
      : (clipErrors[0] || errMsg(clipRes.reason) || 'no clips generated');

    // The slides need the narration's timing; without audio there is nothing to show them against.
    if (!audio && !clipUrls.some(Boolean)) {
      await sr.Lesson.update(lessonId, { status: 'pending_review' });
      throw new HttpError(502, `Media generation failed — audio: ${audioError}${withClips ? `; video: ${videoError}` : ''}`, { video_error: videoError, audio_error: audioError });
    }

    // A scene whose clip failed shows the nearest earlier (or later) clip instead of going blank.
    const filled = clipUrls.map((u, i) => u || clipUrls.slice(0, i).reverse().find(Boolean) || clipUrls.slice(i + 1).find(Boolean) || null);
    const scenes = audio
      ? storyboard.map((s, i) => {
        const start = +audio.spans[i].start.toFixed(2);
        const end = +audio.spans[i].end.toFixed(2);
        return {
          start,
          end,
          title: s.title,
          layout: s.layout,
          points: s.points,
          text: segments[i],
          captions: buildCaptions(segments[i], start, end),
          video_url: filled[i],
        };
      })
      : [];

    // Without clips the lesson has no clip of its own any more: an old one would be the generic footage.
    const update = { status: 'pending_review', video_scenes: scenes.length ? JSON.stringify(scenes) : '', video_url: filled[0] || '' };
    if (audio) update.audio_url = audio.url;
    await sr.Lesson.update(lessonId, update);

    log.info('pipeline.media.done', { lesson_id: lessonId, scenes: storyboard.length, slides_only: slidesOnly, clips: clipUrls.filter(Boolean).length, seconds: audio ? Math.round(audio.seconds) : 0 });
    return {
      ok: true,
      lesson_id: lessonId,
      video_url: update.video_url || lesson.video_url || null,
      audio_url: update.audio_url || lesson.audio_url || null,
      scenes,
      ...(videoError ? { video_error: videoError } : {}),
      ...(audioError ? { audio_error: audioError } : {}),
    };
  } catch (e) {
    log.error('pipeline.media.failed', { lesson_id: lessonId, error: errMsg(e) });
    try {
      await sr.Lesson.update(lessonId, { status: 'pending_review' });
    } catch { /* ignore */ }
    throw asHttpError(e);
  }
}
