import { badRequest } from '@/api/drivers/demo/records';
import { findAll, findOne, insert, mustGet, patch, persist, removeWhere, sleep } from '@/api/drivers/demo/service';

// Canned "AI" generation for the demo backend: lesson packages and assessments, marked "(demo)".

const rotate = (arr, n) => arr.map((_, i) => arr[(i + n) % arr.length]);

function questionSet(title, chapter) {
  return [
    [`Which statement best describes the purpose of “${title}”? (demo)`, [`It applies the ${chapter} guidance to everyday engineering decisions`, 'It removes the need for peer review', 'It only applies to managers', 'It only applies to legacy systems'], 'basic', 'understanding'],
    [`When introducing “${title}” to a team, what should happen first? (demo)`, ['Agree on a shared, written definition and scope', 'Automate everything immediately', 'Skip documentation to move faster', 'Wait for the next incident'], 'basic', 'recall'],
    [`Which of these is an anti-pattern for “${title}”? (demo)`, ['Applying it differently in each team without documenting exceptions', 'Reviewing outcomes regularly', 'Linking decisions back to the playbook', 'Measuring results before and after'], 'intermediate', 'analysis'],
    [`How can a team tell that “${title}” is working? (demo)`, ['Track an agreed metric before and after adoption and review it', 'Count the number of meetings held', 'Ask one senior engineer', 'Assume it works once documented'], 'intermediate', 'application'],
  ].map(([question_text, options, difficulty, cognitive_level], i) => ({
    question_text, options: rotate(options, i % options.length), correct_answer: options[0], difficulty, cognitive_level,
    explanation: `The playbook's ${chapter} chapter ties this practice to clear definitions and measurable outcomes. (demo)`,
  }));
}

function lessonPackage(lesson, chapterTitle, excerpt) {
  const t = lesson.title;
  return {
    video_title: t,
    teaching_objective: `Explain ${t.toLowerCase()} and apply it using the ${chapterTitle} guidance. (demo)`,
    teaching_script: `Welcome to this lesson on ${t}. (demo content — generated by the in-browser demo backend)\n\n`
      + `This lesson comes from the chapter “${chapterTitle}”. ${excerpt}\n\n`
      + `We will start with why the practice exists, then walk through how teams apply it day to day, and finish with the signals that tell you it is working. `
      + `Keep one question in mind throughout: what would change for our users if we got this right?`,
    summary: `${t} applies the ${chapterTitle} guidance with clear definitions, peer review and measurable outcomes. (demo)`,
    key_points: ['Start from a shared, written definition', 'Apply it consistently across teams', 'Review decisions with peers', 'Measure outcomes before and after', 'Revisit the practice regularly (demo)'].join('\n'),
    examples: `A team adopting ${t.toLowerCase()} writes a one-page definition, reviews it in the weekly engineering meeting and tracks one metric for a month. (demo)`,
  };
}

export async function generateLessonContent({ lesson_id: id } = {}, { user }) {
  const lesson = mustGet('Lesson', id);
  const mod = mustGet('Module', lesson.module_id);
  const course = mustGet('Course', mod.course_id);
  patch('Lesson', id, { status: 'generating' });
  persist();
  await sleep(900);
  const chapters = findAll('Chapter', { playbook_id: course.playbook_id });
  const chapter = chapters.find((c) => String(lesson.source_chapter || '').includes(c.title)) || chapters[0];
  const chapterTitle = chapter?.title || mod.title;
  const excerpt = String(chapter?.content || chapter?.summary || '').split(/\n+/).slice(0, 2).join(' ');
  const source = { source_playbook: lesson.source_playbook, source_chapter: lesson.source_chapter, source_section: lesson.source_section };

  removeWhere('Question', { lesson_id: id, assessment_id: { $exists: false } });
  removeWhere('Flashcard', { lesson_id: id });
  const questions = questionSet(lesson.title, chapterTitle).map((q) => insert('Question', { ...q, ...source, lesson_id: id, status: 'pending_review' }, user.id));
  const cards = [
    [`What is the goal of “${lesson.title}”?`, `To apply the ${chapterTitle} guidance consistently and measurably. (demo)`, 'basic'],
    ['What should a team agree on first?', 'A shared, written definition and scope. (demo)', 'basic'],
    ['How do you know it is working?', 'Track an agreed metric before and after adoption. (demo)', 'intermediate'],
  ].map(([front, back, difficulty]) => insert('Flashcard', { lesson_id: id, front, back, difficulty, ...source, status: 'pending_review' }, user.id));

  patch('Lesson', id, { ...lessonPackage(lesson, chapterTitle, excerpt), status: 'pending_review' });
  persist();
  return { ok: true, lesson_id: id, question_count: questions.length, flashcard_count: cards.length };
}

const SPEC = {
  module_test: { count: 15, minutes: 30, label: 'Module Test' },
  course_assessment: { count: 50, minutes: 60, label: 'Final Assessment' },
  certification: { count: 60, minutes: 90, label: 'Certification Exam' },
};

export async function generateAssessment({ course_id: courseId, type = 'course_assessment', module_id: moduleId } = {}, { user }) {
  const course = mustGet('Course', courseId);
  const spec = SPEC[type];
  if (!spec) throw badRequest('type must be module_test, course_assessment or certification');
  if (type === 'module_test' && !moduleId) throw badRequest('module_id is required for module tests');
  await sleep(700);
  const moduleIds = moduleId ? [moduleId] : findAll('Module', { course_id: courseId }).map((m) => m.id);
  const lessons = findAll('Lesson', { module_id: { $in: moduleIds } });
  const pool = findAll('Question', { lesson_id: { $in: lessons.map((l) => l.id) }, assessment_id: { $exists: false } });
  const drafts = pool.length ? pool : lessons.flatMap((l) => questionSet(l.title, findOne('Module', { id: l.module_id })?.title || course.title).map((q) => ({ ...q, lesson_id: l.id })));
  const picked = drafts.slice(0, spec.count);

  const mod = moduleId ? findOne('Module', { id: moduleId }) : null;
  const assessment = insert('Assessment', {
    course_id: courseId, module_id: moduleId, playbook_id: course.playbook_id, type, status: 'pending_review',
    title: `${spec.label}: ${mod?.title || course.title} (demo)`, question_count: picked.length, passing_score: 70, duration_minutes: spec.minutes,
  }, user.id);
  picked.forEach(({ id: _id, created_date: _c, updated_date: _u, created_by_id: _b, ...q }) => insert('Question', {
    ...q, assessment_id: assessment.id, status: 'pending_review',
  }, user.id));
  persist();
  return { ok: true, assessment_id: assessment.id, question_count: picked.length };
}
